version: '3.7'

services:

  cypress:
    build: ./cypress
    ipc: host
    shm_size: '2gb'
    network_mode: host
    depends_on:
      - app
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.json:/e2e/cypress.json