version: '3.7'
services:
  app:
    stdin_open: true
    build: ./
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    networks:
      - client-server-network

networks:
  client-server-network:
    external:
      name: client-server-network