version: '3.7'

services:

  app:
    stdin_open: true
    build: ./
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      REACT_APP_SERVER_URL: http://localhost:9000/api
      SKIP_PREFLIGHT_CHECK: 'true'