version: '3.7'
services:
  app:
    stdin_open: true
    image: docker.pkg.github.com/fga-eps-mds/2020.1-minacademy-frontend/app:homolog
    build:
      context: .
      dockerfile: hml.Dockerfile
    ports:
      - '3000:3000'
    env_file: 
    - .env-hml
    networks:
      - client-server-network

networks:
  client-server-network:
    external:
      name: client-server-network