version: '3.7'
services:
  app:
    stdin_open: true
    restart: always
    image: docker.pkg.github.com/fga-eps-mds/2020.1-minacademy-frontend/app:homolog
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    networks:
      - client-server-network
    environment:
      REACT_APP_SERVER_URL: https://hom-minacademy.tk/api
  

networks:
  client-server-network:
    external:
      name: client-server-network
