version: '3.7'
services:
  app:
    stdin_open: true
    image: docker.pkg.github.com/fga-eps-mds/2020.1-minacademy-frontend/app:homolog
    ports:
      - '3000:3000'
    networks:
      - client-server-network
    environment: 
      SERVER_URL: http://159.89.158.50:9000

networks:
  client-server-network:
    external:
      name: client-server-network