name: Continuous Integration and Delivery

on:
  push:
    branches:
      - develop
      - 50-ci-cd
    pull-request:
      - develop
      - 50-ci-cd

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Modules
      run: npm install
    - name: Run Tests
      run: npm test

  push_to_registry:
    # needs: test
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Push to GitHub Packages
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        name: fga-eps-mds/2020.1-Minacademy-FrontEnd
        tags: homolog
        context: ./
        default_branch: 50-ci-cd
        dockerfile: prod.Dockerfile
