name: Continuous Integration - PR's Tests

on:
  pull_request:

jobs:
  eslint: 
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Modules
      run: npm install
    - name: Run Tests
      run: npm test