name: Continuous Integration - PR's Tests

on:
  pull_request:
    branches:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Modules
      run: npm install
    - name: Run Tests
      run: npm test